# Generated by Django 2.2.7 on 2019-11-24 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=20)),
                ('game_state', models.CharField(max_length=100)),
                ('against_ai', models.BooleanField()),
                ('opponent_name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
