# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Connect4AI')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Connect4AI')
    _Connect4AI = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Connect4AI', [dirname(__file__)])
        except ImportError:
            import _Connect4AI
            return _Connect4AI
        try:
            _mod = imp.load_module('_Connect4AI', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Connect4AI = swig_import_helper()
    del swig_import_helper
else:
    import _Connect4AI
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Connect4AI.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _Connect4AI.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _Connect4AI.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _Connect4AI.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _Connect4AI.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _Connect4AI.SwigPyIterator_equal(self, x)

    def copy(self):
        return _Connect4AI.SwigPyIterator_copy(self)

    def next(self):
        return _Connect4AI.SwigPyIterator_next(self)

    def __next__(self):
        return _Connect4AI.SwigPyIterator___next__(self)

    def previous(self):
        return _Connect4AI.SwigPyIterator_previous(self)

    def advance(self, n):
        return _Connect4AI.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _Connect4AI.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _Connect4AI.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _Connect4AI.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _Connect4AI.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _Connect4AI.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _Connect4AI.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _Connect4AI.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class GameState(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GameState, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GameState, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _Connect4AI.new_GameState(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    WIDTH = _Connect4AI.GameState_WIDTH
    HEIGHT = _Connect4AI.GameState_HEIGHT
    bottom_mask = _Connect4AI.GameState_bottom_mask
    board_mask = _Connect4AI.GameState_board_mask

    def playCol(self, col):
        return _Connect4AI.GameState_playCol(self, col)

    def playMove(self, move):
        return _Connect4AI.GameState_playMove(self, move)

    def possible(self):
        return _Connect4AI.GameState_possible(self)

    def play(self, seq):
        return _Connect4AI.GameState_play(self, seq)

    def play_board_state(self, board_state, curr_stone):
        return _Connect4AI.GameState_play_board_state(self, board_state, curr_stone)

    def unique_key(self):
        return _Connect4AI.GameState_unique_key(self)

    def nbMoves(self):
        return _Connect4AI.GameState_nbMoves(self)

    def possibleNonLosingMoves(self):
        return _Connect4AI.GameState_possibleNonLosingMoves(self)

    def canWinNext(self):
        return _Connect4AI.GameState_canWinNext(self)

    def isWinningMove(self, col):
        return _Connect4AI.GameState_isWinningMove(self, col)
    if _newclass:
        column_mask = staticmethod(_Connect4AI.GameState_column_mask)
    else:
        column_mask = _Connect4AI.GameState_column_mask

    def canPlay(self, col):
        return _Connect4AI.GameState_canPlay(self, col)

    def moveScore(self, move):
        return _Connect4AI.GameState_moveScore(self, move)

    def winning_position(self):
        return _Connect4AI.GameState_winning_position(self)

    def opponent_winning_position(self):
        return _Connect4AI.GameState_opponent_winning_position(self)
    if _newclass:
        compute_winning_position = staticmethod(_Connect4AI.GameState_compute_winning_position)
    else:
        compute_winning_position = _Connect4AI.GameState_compute_winning_position
    __swig_destroy__ = _Connect4AI.delete_GameState
    __del__ = lambda self: None
GameState_swigregister = _Connect4AI.GameState_swigregister
GameState_swigregister(GameState)

def GameState_column_mask(col):
    return _Connect4AI.GameState_column_mask(col)
GameState_column_mask = _Connect4AI.GameState_column_mask

def GameState_compute_winning_position(position, mask):
    return _Connect4AI.GameState_compute_winning_position(position, mask)
GameState_compute_winning_position = _Connect4AI.GameState_compute_winning_position

class TranspositionTable(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TranspositionTable, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TranspositionTable, name)
    __repr__ = _swig_repr

    def __init__(self, size):
        this = _Connect4AI.new_TranspositionTable(size)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def reset(self):
        return _Connect4AI.TranspositionTable_reset(self)

    def put(self, key, val):
        return _Connect4AI.TranspositionTable_put(self, key, val)

    def get(self, key):
        return _Connect4AI.TranspositionTable_get(self, key)
    __swig_destroy__ = _Connect4AI.delete_TranspositionTable
    __del__ = lambda self: None
TranspositionTable_swigregister = _Connect4AI.TranspositionTable_swigregister
TranspositionTable_swigregister(TranspositionTable)

class Solver(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Solver, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Solver, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _Connect4AI.new_Solver(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def reset(self):
        return _Connect4AI.Solver_reset(self)

    def solve(self, GS):
        return _Connect4AI.Solver_solve(self, GS)

    def getNodeCount(self):
        return _Connect4AI.Solver_getNodeCount(self)
    __swig_destroy__ = _Connect4AI.delete_Solver
    __del__ = lambda self: None
Solver_swigregister = _Connect4AI.Solver_swigregister
Solver_swigregister(Solver)

# This file is compatible with both classic and new-style classes.


